-- PostgreSQL / Neon-compatible employee portal schema and seed data.
-- Run this script while connected to the target Neon database. It replaces the
-- application tables below, matching the destructive behavior of the
-- original MySQL dump.

BEGIN;

SET LOCAL TIME ZONE 'UTC';

DROP TABLE IF EXISTS hr_empfamilydet, hr_empexamdet, hr_update_request, up_emp,
  hr_batch_control, admin_user CASCADE;

CREATE TABLE admin_user (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) NOT NULL,
  password_hash varchar(255) NOT NULL,
  display_name varchar(200),
  user_type varchar(20) NOT NULL DEFAULT 'ADMIN',
  active_yn char(1) NOT NULL DEFAULT 'Y',
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_admin_username UNIQUE (username),
  CONSTRAINT ck_admin_user_type CHECK (user_type IN ('ADMIN', 'SUPER_ADMIN')),
  CONSTRAINT ck_admin_active_yn CHECK (active_yn IN ('Y', 'N'))
);

CREATE TABLE hr_batch_control (
  batch_no varchar(100) PRIMARY KEY,
  status varchar(10) NOT NULL DEFAULT 'INACTIVE',
  started_at timestamptz,
  closed_at timestamptz,
  created_by varchar(150),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_batch_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX ix_batch_status ON hr_batch_control (status);

CREATE TABLE up_emp (
  emp_entry_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meritlist_id varchar(100) NOT NULL,
  class_id varchar(100) NOT NULL,
  ipi varchar(50),
  approval_status varchar(10) NOT NULL DEFAULT 'DRAFT',
  approved_by varchar(100),
  approved_at timestamptz,
  name varchar(1000),
  batch_no varchar(100) NOT NULL,
  birthdate date,
  bld_group varchar(30),
  gender char(1),
  religion char(1),
  nationality varchar(50),
  marital_status char(1),
  email varchar(300),
  phone varchar(30),
  phone1 varchar(50),
  height varchar(300),
  weight varchar(300),
  nid varchar(30),
  permanent_village varchar(300),
  permanent_post varchar(300),
  permanent_thana varchar(300),
  permanent_district varchar(300),
  present_village varchar(300),
  present_post varchar(300),
  present_thana varchar(300),
  present_district varchar(300),
  emgrcny_person varchar(300),
  emgrcny_relation varchar(50),
  emgrcny_address varchar(255),
  emgrcny_phone varchar(20),
  father_name varchar(300),
  father_phone varchar(20),
  mother_name varchar(300),
  mother_phone varchar(20),
  spouse_name varchar(300),
  spose_marriage_date date,
  spose_occupation varchar(300),
  spouse_phone varchar(30),
  grnt_name varchar(300),
  grnt_rele varchar(100),
  grnt_father varchar(300),
  grnt_present_add varchar(255),
  grnt_permanet_add varchar(255),
  grnt_nationality varchar(50),
  grnt_proffession varchar(300),
  grnt_nid varchar(30),
  grnt_mobile varchar(20),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz,
  CONSTRAINT uk_emp_batch_merit_class UNIQUE (batch_no, meritlist_id, class_id),
  CONSTRAINT uk_emp_ipi UNIQUE (ipi),
  CONSTRAINT fk_up_emp_batch FOREIGN KEY (batch_no)
    REFERENCES hr_batch_control (batch_no),
  CONSTRAINT ck_emp_approval_status CHECK (
    approval_status IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED')
  )
);

CREATE INDEX ix_up_emp_batch ON up_emp (batch_no);
CREATE INDEX ix_emp_verify ON up_emp (meritlist_id, class_id, phone);
CREATE INDEX ix_up_emp_approval ON up_emp (approval_status);

CREATE TABLE hr_empexamdet (
  slno bigint NOT NULL,
  emp_entry_id bigint NOT NULL,
  empcode varchar(50),
  examname varchar(170),
  examgroup varchar(170),
  board varchar(1000),
  clas varchar(300),
  passyear varchar(100),
  remarks varchar(100),
  institute varchar(500),
  subject_name varchar(200),
  PRIMARY KEY (emp_entry_id, slno),
  CONSTRAINT fk_exam_emp_entry FOREIGN KEY (emp_entry_id)
    REFERENCES up_emp (emp_entry_id) ON DELETE CASCADE
);

CREATE INDEX ix_exam_entry ON hr_empexamdet (emp_entry_id);
CREATE INDEX ix_exam_empcode ON hr_empexamdet (empcode);

CREATE TABLE hr_empfamilydet (
  emp_entry_id bigint NOT NULL,
  empcode varchar(50),
  fname varchar(100),
  f_ocup varchar(70),
  f_add varchar(100),
  phone varchar(25),
  child_nos bigint NOT NULL,
  birth_date date,
  PRIMARY KEY (emp_entry_id, child_nos),
  CONSTRAINT fk_family_emp_entry FOREIGN KEY (emp_entry_id)
    REFERENCES up_emp (emp_entry_id) ON DELETE CASCADE
);

CREATE INDEX ix_family_entry ON hr_empfamilydet (emp_entry_id);
CREATE INDEX ix_family_empcode ON hr_empfamilydet (empcode);

CREATE TABLE hr_update_request (
  request_id uuid PRIMARY KEY,
  emp_entry_id bigint NOT NULL,
  ipi varchar(50),
  meritlist_id varchar(100) NOT NULL,
  class_id varchar(100) NOT NULL,
  batch_no varchar(100) NOT NULL,
  request_note varchar(1000),
  requested_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status varchar(10) NOT NULL DEFAULT 'PENDING',
  approved_at timestamptz,
  approved_until timestamptz,
  approved_by varchar(150),
  admin_remarks varchar(1000),
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_req_batch FOREIGN KEY (batch_no)
    REFERENCES hr_batch_control (batch_no),
  CONSTRAINT fk_req_emp_entry FOREIGN KEY (emp_entry_id)
    REFERENCES up_emp (emp_entry_id),
  CONSTRAINT ck_request_status CHECK (
    status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')
  )
);

CREATE INDEX ix_req_entry_status ON hr_update_request (emp_entry_id, status);
CREATE INDEX ix_req_approved_until ON hr_update_request (approved_until);
CREATE INDEX ix_req_batch ON hr_update_request (batch_no);

-- PostgreSQL does not support MySQL's ON UPDATE CURRENT_TIMESTAMP clause.
-- These triggers preserve that behavior for the two tables that used it.
CREATE OR REPLACE FUNCTION employee_portal_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_batch_control_updated_at
BEFORE UPDATE ON hr_batch_control
FOR EACH ROW EXECUTE FUNCTION employee_portal_set_updated_at();

CREATE TRIGGER trg_update_request_updated_at
BEFORE UPDATE ON hr_update_request
FOR EACH ROW EXECUTE FUNCTION employee_portal_set_updated_at();

INSERT INTO admin_user
  (user_id, username, password_hash, display_name, user_type, active_yn, created_at)
VALUES
  (1, 'sadiq', '$2b$12$TU3cNVhC9GBiWaBpIeEygOwsCcgazhLIDAU/ZAL8SZ75N/Zsa82HW',
   'Administrator', 'SUPER_ADMIN', 'Y', '2026-08-27 11:50:07+00'),
  (4, 'mahmudalam', '$2b$12$jxXbF7fdaMCVLkXaeaXZhOCyDPfV33348XDZASDFDVPChSlsnSkPC',
   'Mahmud Alam', 'ADMIN', 'Y', '2026-08-31 11:45:08+00');

INSERT INTO hr_batch_control
  (batch_no, status, started_at, closed_at, created_by, created_at, updated_at)
VALUES
  ('BATCH-2026-01', 'ACTIVE', '2026-08-27 12:13:13+00', NULL,
   'mahmudalam', '2026-08-27 12:13:11+00', '2026-08-31 11:46:13+00'),
  ('BATCH-2026-02', 'INACTIVE', '2026-08-31 10:12:42+00',
   '2026-08-31 11:45:59+00', 'sadiq', '2026-08-31 10:12:38+00',
   '2026-08-31 11:45:59+00');

INSERT INTO up_emp (
  emp_entry_id, meritlist_id, class_id, ipi, approval_status, approved_by,
  approved_at, name, batch_no, birthdate, bld_group, gender, religion,
  nationality, marital_status, email, phone, phone1, height, weight, nid,
  permanent_village, permanent_post, permanent_thana, permanent_district,
  present_village, present_post, present_thana, present_district,
  emgrcny_person, emgrcny_relation, emgrcny_address, emgrcny_phone,
  father_name, father_phone, mother_name, mother_phone, spouse_name,
  spose_marriage_date, spose_occupation, spouse_phone, grnt_name, grnt_rele,
  grnt_father, grnt_present_add, grnt_permanet_add, grnt_nationality,
  grnt_proffession, grnt_nid, grnt_mobile, created_at, updated_at
)
VALUES
  (
    1, '101', '01', 'IPI-009129', 'APPROVED', 'sadiq',
    '2026-08-27 12:55:21+00', 'Md. Sadiqur Rahman', 'BATCH-2026-01',
    '1997-12-30', 'AB-', 'M', 'I', 'Bangladeshi', 'U',
    'shadiqur.it@gmail.com', '01996200797', '01709645125', '5'' 3"', '62kg',
    '4203692415', 'Baniabari', 'Mahmudpur', 'Melandaha', 'Jamalpur',
    'Baniabari', 'Mahmudpur', 'Melandaha', 'Jamalpur', 'Ataur Rahman',
    'Father', NULL, '01728183469', 'Ataur Rahman', '01728183469',
    'Sawda Begum', '01728183469', 'Arafat Jahan', '2007-12-09', 'Student',
    '01996200797', 'Ataur Rahman', 'Father', 'AB Samad Mondol',
    'Baniabari, Mahmudpur, Melandaha, Jamalpur',
    'Baniabari, Mahmudpur, Melandaha, Jamalpur', 'Bangladeshi',
    NULL, NULL, NULL, '2026-08-27 12:17:40+00', '2026-08-30 16:32:54+00'
  ),
  (
    2, '1', '1', NULL, 'APPROVED', 'sadiq', '2026-08-30 04:02:52+00',
    'Mahmud hasan', 'BATCH-2026-01', '2026-08-21', 'B+', 'M', 'I',
    'Bangladesh', 'M', 'mahmudhasanalam91@gmail.com', '01709649354',
    '01918589368', '5.5', '56 kg', '7772522400', 'Chackbara', 'Hainbari',
    'Shyamanagar', 'Satkhira', 'Chackbara', 'Hainbari', 'Shyamanagar',
    'Satkhira', 'Samim', 'Brother',
    '3 Asadgate, Tanin Center, Mihammadpur, Dhaka', '01709649364',
    'Mostafa shahidullah', '01912379624', 'Saleha khatun', '01954381368',
    'Sayedatun Neaa', '2026-08-28', 'Nurse', '01779133646',
    'Mostafa shahidullah', 'Father', 'Nojib mollah',
    '3 Asadgate, Tanin Center, Mihammadpur, Dhaka', 'Bosila', '4448882920',
    'Business', '9999yywiwi2', '01012379624', '2026-08-30 03:20:57+00',
    '2026-08-30 04:02:52+00'
  );

INSERT INTO hr_empexamdet
  (slno, emp_entry_id, empcode, examname, examgroup, board, clas, passyear,
   remarks, institute, subject_name)
VALUES
  (1, 1, 'IPI-009129', 'SSC / Dakhil', 'General', 'Madrasah', '4.56',
   '2012', NULL, NULL, NULL),
  (1, 2, NULL, 'SSC / Dakhil', 'Science', 'Jeshore', 'R.18',
   '2006', 'Ok', 'Satkhira', 'Science');

-- Explicit identity values were loaded above, so move each sequence beyond
-- the highest imported key before the application starts inserting rows.
SELECT setval(
  pg_get_serial_sequence('admin_user', 'user_id'),
  (SELECT max(user_id) FROM admin_user),
  true
);

SELECT setval(
  pg_get_serial_sequence('up_emp', 'emp_entry_id'),
  (SELECT max(emp_entry_id) FROM up_emp),
  true
);

COMMIT;
